### ISSUE TITLE
How to set directory or file to be watched without relying on a previous task

### ISSUE THREAD

**Issue by Francisc** [leo/gulp-refresh#3]
Hello,

How can I watch a folder or file without pipe()-ing livereload to a previous task.
I would like to watch a folder or file wihout running a new task:

Something like this, no sass or css file before.

```js
gulp.task('livereload', function() {
    livereload({basePath:DIST_FOLDER,start:true});
    livereload.listen();
});
```

^ That's not a working example, it's for illustration.

Note: Migrated from https://github.com/vohof/gulp-livereload/issues/103.

**Comment by leo** [comment]
If you just want to watch the files within your `DIST_FOLDER`, you'll have to create two separate tasks:

```js
const livereload = require('gulp-refresh')

gulp.task('reload', () => {
  livereload.reload()
})

gulp.task('watch', () => {
  livereload.listen()
  gulp.watch(DIST_FOLDER, ['reload'])
})
```

In this case, `DIST_FOLDER` could be something like `dist/**/*`, if your destination folder is called "dist". Does this answer your question?

**Comment by leo** [comment]
Please also keep in mind that you shouldn't use both `livereload.listen()` **and** the `start` option together. Why? Because each of them already automatically starts the server, so you just need to use one of them.

**Comment by leo** [comment]
Closing this now, since it seems to be solved. Please re-open if not, @Francisc.
