### ISSUE TITLE
Livereload Not Refreshing

### ISSUE THREAD

**Issue by 0Neji** [leo/gulp-refresh#4]
Hi,

I've just recently switched over from gulp-livereload to you forked version because I was having some trouble getting it to work. I've been using it for a few years with no problem but it's almost completely stopped at this point. I had hoped a switch would fix my issue but here I am.

Anyway, I'm getting a message to say that the stylesheet is reloaded but my browser never refreshes. I'm using Chrome and the livereload extension - I've also made sure I've activated it before changing my code. It's also running on a local server. Here's my gulpfile.js:

	var gulp         = require('gulp'),
		sass         = require('gulp-sass'),
		sourcemaps   = require('gulp-sourcemaps'),
		autoprefixer = require('gulp-autoprefixer'),
		livereload   = require('gulp-refresh');

	var sass_paths = '_src/sass/**/**.scss';
	var css_path = 'umbraco/assets/css';

	var sass_options = {
		errLogToConsole: true,
		outputStyle: 'expanded'
	};

	gulp.task('sass', function () {
		return gulp
			.src(sass_paths)
			.pipe(sourcemaps.init())
			.pipe(sass(sass_options).on('error', sass.logError))
			.pipe(sourcemaps.write())
			.pipe(autoprefixer())
			.pipe(gulp.dest(css_path))
			.pipe(livereload());
	});

	gulp.task('watch', function()
	{
		livereload.listen();
		gulp.watch(sass_paths, ['sass']);
		gulp.watch(['**/*.cshtml']).on('change', function(file) { livereload.changed(file.path) })
	});

	gulp.task('default', ['sass', 'watch']);

I can't see any different whatsoever with the way it's set up in the docs - what am I doing wrong here?

**Comment by leo** [comment]
It's not supposed to actually reload the browser when a stylesheet changes. If it's just CSS (like in your example), it will simply inject the updated file into your browser.

Have you already tried making some changes? Or did you just wait for a reload? :blush:

**Comment by 0Neji** [comment]
Yes, sorry, bad terminology on my part. I make changes to my scss files but the page never updates. It's currently only a body tag with a bg colour. If I refresh the page manually, the changes show up but they never seem to get injected to the browser.

As I said, I have used this workflow for a few years with no issues, it's only recently that this has cropped up.

**Comment by leo** [comment]
Okay, no problem. Is your complete setup available on GitHub or would you mind sharing it with me? Because your gulpfile seems fine for me.

Maybe one thing I would do differently is put the `autoprefixing` step before the `sourcemap.write` step...

**Comment by leo** [comment]
If not, have you tried using a livereload middleware instead of that chrome extension? I'm asking because it seems to be very old and I honestly wouldn't recommend it anymore.

**Comment by 0Neji** [comment]
I'm just going through the setup so this is really the first thing that I was trying to there isn't much to see - I've created a new repo for it however - https://github.com/0Neji/gulp-starter

I'm not familiar with livereload middleware - could you point me in the right direction to set it up?

Thanks for all the help btw, it's really appreciated.

**Comment by leo** [comment]
Ahh, okay. It looks like you're trying to build a static site. In this case, you should give [Browser Sync](https://browsersync.io/docs/gulp/) a try. It allows you to specify a directory from which the site should be served and automatically handles all the livereloading for you.

`gulp-refresh` is better if you'd like to create a non-static site. Because in those cases, you'll then be able to add so-called "middlewares" to your server-side code which will append the livereloading script to your site. But as I said, you're site seems to be static - so give BrowserSync a try! :blush:

**Comment by 0Neji** [comment]
It's actually going to be an Umbraco site - I'm literally just dropping the barebones in. The Umbraco set up will be done in Visual Studio and will have it's own server. I believe the css will already get injected in that instance but I also use this workflow for a few Wordpress sites running locally on XAMPP.

By middleware, do you mean a server? As in, have gulp handle the server rather than going through XAMPP? I'm going to have a look into this as well.

Thanks!

**Comment by leo** [comment]
Hmm...

> By middleware, do you mean a server? As in, have gulp handle the server rather than going through XAMPP? I'm going to have a look into this as well.

Yep. But all those middlewares are specifically made for Node.js apps. Are you building a Node.js application currently?

**Comment by 0Neji** [comment]
No, just Wordpress and Umbraco currently.

**Comment by joshkpeterson** [comment]
Had the same issue. I'm using Sublime Text 3, and turns out the problem was I had a ST3 livereload plugin installed. Removing that plugin solved the problem and allowed the page to update.

**Comment by 0Neji** [comment]
Interesting, I do have a livereload plugin installed in Sublime, it never worked so never got used but neither did it get removed. I'll get rid of it and give it a try. Thanks for the info!

**Comment by leo** [comment]
@0Neji Does it work now? :blush:

**Comment by lucien144** [comment]
Hi guys, I can confirm that the @joshkpeterson solution has worked for me.

**Comment by 0Neji** [comment]
Hi,

Apologies for the late reply - I know it's closed but I just wanted to confirm that this does indeed now work as expected.

Thanks for the help guys!

**Comment by leo** [comment]
Yey! Great to hear :blush:
